@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxMDgsImV4cCI6MTY1MDY1MDYxMn0.R9siGqvwwGZ8AiBpdgGAzbhLJJBo3xBuhERJY_sy5Ro

POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "amanda",
  "email": "amanda@test.com",
  "password": "password",
  "password_confirmation": "password",
  "username": "amanda",
  "home_airport": "ORD",
  "avitar": "image_url"
}

### Sessions create (login)
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "amanda@test.com",
  "password": "password"
}

### airports create 
# POST http://localhost:3000/airports
# Content-Type: application/json

# {
#   "iata":"sgf",
#   "icao":"ksgf",
#   "name":"springfield airport",
#   "location":"springfield, mo"
# }

### favorites create
POST http://localhost:3000/favorites
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
  "iata":"msy"
}

### favorites delete
DELETE http://localhost:3000/favorites/182
Authorization: Bearer {{jwt}}

### user delete
DELETE http://localhost:3000/users/1
Authorization: Bearer {{jwt}}

### user update
PATCH http://localhost:3000/users
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
  "home_airport":"bbg"
}

### favorites index
GET http://localhost:3000/favorites
Authorization: Bearer {{jwt}}
Content-Type: application/json


### user show
GET http://localhost:3000/users
Authorization: Bearer {{jwt}}
Content-Type: application/json


### get weather
GET https://avwx.rest/api/metar/KJFK?token=_IX6kr0_tT4wusRSOyIkJDqIyx7TUqI3099F7E9h70w	
Content-Type: application/json
