@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxMDIsImV4cCI6MTY1MDI2ODIwM30.5UCBfDX47u4n0ZuTRcF25WRWRoaKXWKwM1HpIa4Lu8U

POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "eliot",
  "email": "eliot@test.com",
  "password": "password",
  "password_confirmation": "password",
  "username": "eliotpitman",
  "home_airport": "KPLK",
  "avitar": "image_url"
}

### Sessions create (login)
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "eliot@test.com",
  "password": "password"
}

### airports create 
POST http://localhost:3000/airports
Content-Type: application/json

{
  "iata":"sgf",
  "icao":"ksgf",
  "name":"springfield airport",
  "location":"springfield, mo"
}

### favorites create
POST http://localhost:3000/favorites
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
  "iata":"lax"
}

### favorites delete
DELETE http://localhost:3000/favorites/152
Authorization: Bearer {{jwt}}

### user delete
DELETE http://localhost:3000/users/1
Authorization: Bearer {{jwt}}

### user update not working
PATCH http://localhost:3000/users
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
  "home_airport":"lax"
}

### favorites index
GET http://localhost:3000/favorites
Authorization: Bearer {{jwt}}
Content-Type: application/json


### user show
GET http://localhost:3000/users
Authorization: Bearer {{jwt}}
Content-Type: application/json


### get weather
GET https://private-47724b-avwx.apiary-mock.com/api/metar/KJFK
Authorization: Bearer key
Content-Type: application/json
