@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxMDIsImV4cCI6MTY1MDE4NzQ1MX0.Vc0cWUUs0-9MBrYUCe6tXnUin2ooYjE3YuQBLliqdPQ

POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "eliot",
  "email": "eliot@test.com",
  "password": "password",
  "password_confirmation": "password",
  "username": "eliotpitman",
  "home_airport": "KPLK",
  "avitar": "image_url"
}

### Sessions create (login)
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "eliot@test.com",
  "password": "password"
}

### airports create 
POST http://localhost:3000/airports
Content-Type: application/json

{
  "iata":"sgf",
  "icao":"ksgf",
  "name":"springfield airport",
  "location":"springfield, mo"
}

### favorites create
POST http://localhost:3000/favorites
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
  "iata":"bbg"
}

